### ISSUE TITLE
The test for #create is incomplete.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/translating-orm-to-ar#5]
Hello. This is a VERY minor issue, but I wanted to bring it to your attention. I noticed that the test for #create looks like this:

```ruby
describe '.create' do
    it 'takes in a hash of attributes and uses metaprogramming to create a new dog object. Then it uses the #save method to save that dog to the database' do
      dog = Dog.create(name: "Ralph", breed: "lab")
      expect(dog.name).to eq("Ralph")
    end
  end
```

The test makes sure that a Dog object is instantiated, but it doesn't check to see if it's saved to the database. That's a pretty easy fix, though. I think all you have to do is add this line of code to the test:

```ruby
expect(dog.id).to eq(1)
```

I hope this helps (and have a Merry Christmas, by the way!)

Sdcrouse

**Comment by sgharms** [comment]
@Sdcrouse Per the [documentation](https://guides.rubyonrails.org/active_record_basics.html#create), `#create`

> [will] call will create and save a new record into the database:

In the event of a the implicit `save` failing, `false` will be returned and the test will fail. So I don't _think_ the test is built around an incorrect assumption or is leaving something exposed. If you can provide a case where a false positive is found, please re-open.

**Comment by Sdcrouse** [comment]
Thanks for looking into that. I should have checked the ActiveRecord code for #create; I didn't consider that it might be written differently than the way that other labs had us write it. I'll be sure to take a closer look at that.
