### ISSUE TITLE
JSON gem dependency issue

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/translating-orm-to-ar#6]
I could not run the tests, because Active Record has a dependency on JSON, which was not included in your gemfile. I keep getting this error: 

`An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3' --source 'https://rubygems.org/'` succeeds
before bundling.

In Gemfile:
  activerecord was resolved to 4.2.5, which depends on
    activemodel was resolved to 4.2.5, which depends on
      activesupport was resolved to 4.2.5, which depends on
        json
`

**Comment by JoeQuattrone** [comment]
UPDATE: I installed json 1.8.5 as version 1.8.3 would not install. I then ran `bundle update` which updated the gemfile.lock and ran the tests. Only 4 out 8 of my tests passed I kept getting this error for the 4 failed tests: 

 Dog .update updates the record associated with a given instance
     Failure/Error: teddy_jr = Dog.find_by_name("Teddy Jr.")
     
     TypeError:
       Cannot visit Integer

The solution to this was simply deleting the gemfile.lock

**Comment by drakeltheryuujin** [comment]
Hi @JoeQuattrone,

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that others may not have the same problems.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
