### ISSUE TITLE
I would like to reopen an issue regarding the test for #create.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/translating-orm-to-ar#8]
Hello! I am reopening this previously resolved issue: [https://github.com/learn-co-curriculum/translating-orm-to-ar/issues/5](https://github.com/learn-co-curriculum/translating-orm-to-ar/issues/5)

My reason for this is that I found some new information. Before I get to that, I recognize that this is a VERY unlikely edge case, so please feel free to take it or leave it. 

According to [the official documentation](https://apidock.com/rails/v3.1.0/ActiveRecord/Base/create/class), #create 

> Creates an object (or multiple objects) and saves it to the database, if validations pass. The resulting object is returned whether the object was saved successfully to the database or not.

This is assuming that I found the correct version of the #create method. If that IS the correct version, then that means that the current test for #create can theoretically pass with a false positive if something goes wrong with the implicit call to #save. The way to fix that is to add this line to the test:

`expect(dog.id).to eq(1)`

Again, since this is only an edge case, I'm guessing it doesn't need to be the highest priority. Thanks for looking into this, regardless!

---Sdcrouse

**Comment by maxwellbenton** [comment]
Hey @Sdcrouse,

You are correct! I took a look at this lab and your suggestion works with the expected solution. I am not 100% sure what would be needed to create a false positive - something would need to go wrong with ActiveRecord or its `create` method would need to overwritten within the Dog class, I suppose, but the additional expect has been added to the tests in this lesson.

Thank you for your contribution!
